development:
  adapter: postgresql
  encoding: unicode
  database: rental_yield_calculator_development
  pool: 5
  username: jlieu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rental_yield_calculator_test
  pool: 5
  username: jlieu
  password:
